const translations = {
  "pl": {
    "tab_start": "Start",
    "tab_planety": "Planety",
    "tab_punkty": "Punkty",
    "tab_detale": "Detale",
    "start_noPlanets": "Stwórz nową planetę lub importuj dane JSON",
    "start_addPoint": "Dodaj punkt",
    "start_label_x": "X (−90 do 90)",
    "start_label_y": "Y (−180 do 180)",
    "start_label_pointName": "Nazwa punktu",
    "start_label_type": "Typ",
    "type_resource": "Zasób",
    "type_base": "Baza",
    "type_ruins": "Ruiny",
    "type_structure": "Struktura",
    "type_other": "Inne",
    "start_label_notes": "Notatki",
    "start_btn_addPoint": "Dodaj punkt",
    "start_scaling": "Skalowanie globu i punktów",
    "start_pointScale": "Skalowanie punktów",
    "start_pointsDistanceMultiplier": "Wysokość słupka",
    "start_globeZoom": "Zoom globu",
    "start_btn_reset": "Reset",
    "start_autoRotate": "Obracanie globu",
    "start_importExport": "Import/Eksport",
    "start_btn_export": "Eksport JSON",
    "start_languageSelector": "Wybierz język",

 "planet_search_placeholder": "Nazwa planety...",
  "planet_filter_biome": "Biom",
  "planet_filter_biomeAlias": "Alias biomu",
  "planet_filter_resource": "Pierwiastki",
  "planet_filter_allResources": "Wszystkie pierwiastki",

  "planet_btn_search": "Szukaj",
  "planet_new_name": "Nazwa nowej planety",
  "planet_btn_create": "Stwórz nową planetę",
  "planet_label_isMoon": "Twórz jako księżyc",
  "planet_btn_generateName": "Generuj nazwę",
  "planet_label_color": "Wybierz kolor",
  "planet_texture_url": "URL tekstury",
  "planet_btn_setTexture": "Ustaw teksturę",
  "planet_btn_setColor": "Zmień kolor",

  "planet_btn_rename": "Zmień nazwę",
  "planet_btn_delete": "Usuń planetę",
  "planet_edit_name": "Nowa nazwa planety",
  "planet_btn_accept": "Akceptuj",
  "planet_btn_cancel": "Anuluj",

  "res_copper": "Miedź",
  "res_cadmium": "Kadm",
  "res_emeril": "Emeril",
  "res_indium": "Ind",
  "res_quartz": "Kwarcyt",
  "res_chromatic_metal": "Metal chromatyczny",
  "res_paraffinium": "Parafin",
  "res_pyrite": "Piryt",
  "res_ammonia": "Amoniak",
  "res_uranium": "Uran",
  "res_dioxite": "Dioksyt",
  "res_phosphorus": "Fosfor",
  "res_basalt": "Bazalt",
  "res_crystal_helium": "Skrystalizowany hel",
  "res_lithium": "Lit",
  "res_cobalt": "Kobalt",
  "res_silver": "Srebro",
  "res_gold": "Złoto",
  "res_magnetised_ferrite": "Namagnesowany ferryt",
  "res_sodium": "Sód",
  "res_salt": "Sól",
  "res_rusty_metal": "Zardzewiały metal",

"points_filter_label": "Filtruj",
  "points_filter_resource": "Zasób",
  "points_filter_base": "Baza",
  "points_filter_ruins": "Ruiny",
  "points_filter_structure": "Struktura",
  "points_filter_other": "Inne",
  "points_filter_poles": "Bieguny",
  "points_filter_myloc": "Moja lokalizacja",
  "points_extra_filters_label": "Filtry dodatkowe",
  "points_extra_mined": "Wydobyty",
  "points_extra_visited": "Odwiedzony",
  "points_extra_unmined": "Niewydobyty",
  "points_extra_unvisited": "Nieodwiedzony",
  "points_sort_label": "Sortuj",
  "sort_name_asc": "Nazwa A–Z",
  "sort_name_desc": "Nazwa Z–A",
  "sort_type": "Typ",
  "sort_newest": "Najnowsze",
  "sort_oldest": "Najstarsze",

  "detail_galaxy_label": "Galaktyka",
  "detail_galaxy_placeholder": "Wybierz galaktykę...",
  "detail_star_system_label": "Układ gwiezdy",
  "detail_planet_system_label": "Układ planetarny",
  "detail_biome_label": "Biom",
  "detail_biome_none": "-- Wybierz biom --",
  "biome_lush": "Bujny",
  "biome_barren": "Jałowy",
  "biome_dead": "Martwy",
  "biome_exotic": "Egzotyczny",
  "biome_mega_exotic": "Mega Egzotyczny",
  "biome_hot": "Spalony",
  "biome_frozen": "Zamrożony",
  "biome_toxic": "Toksyczny",
  "biome_radioactive": "Napromieniowany",
  "biome_swamp": "Bagno",
  "biome_volcanic": "Wulkaniczny",
  "biome_gas_giant": "Gazowy Gigant",

  "detail_biome_alias_label": "Alternatywna nazwa biomu",
  "detail_biome_alias_none": "-- Wybierz alternatywną nazwę --",
  "detail_weather_label": "Pogoda",
  "weather_none": "-- wybierz --",
  "weather_none_atmosphere": "Brak atmosfery",
  "weather_sunny": "Słonecznie",
  "weather_cool": "Chłodno",
  "weather_frosty": "Mroźno",
  "weather_warm": "Ciepło",
  "weather_hot": "Gorąco",
  "weather_humid": "Wilgotno",
  "weather_rainy": "Deszczowo",
  "weather_stormy": "Burzowo",
  "weather_radioactive": "Radioaktywne",
  "weather_toxic": "Toksyczne",
  "weather_acidic": "Kwasyczne",
  "weather_dusty": "Pyłowe",
  "weather_volcanic": "Wulkaniczne",
  "weather_sandstorm": "Burze piaskowe",
  "weather_tornado": "Tornada",
  "weather_meteor": "Meteoryty",
  "weather_firestorm": "Burze ogniste",
  "weather_high_pressure": "Wysokie ciśnienie",
  "weather_low_pressure": "Niskie ciśnienie",
  "weather_magnetic": "Burze magnetyczne",
  "weather_electric": "Burze elektryczne",

  "detail_sentinels_label": "Strażnicy",
  "sentinels_none": "-- wybierz --",
  "sentinels_passive": "Pasywne",
  "sentinels_no": "Brak",
  "sentinels_relaxed": "Zrelaksowane",
  "sentinels_limited": "Ograniczone",
  "sentinels_low": "Niskie",
  "sentinels_low_security": "Niskie bezpieczeństwo",
  "sentinels_minimal": "Minimalne",
  "sentinels_active": "Aktywne",
  "sentinels_medium": "Średnie",
  "sentinels_standard": "Standardowe",
  "sentinels_typical": "Typowe",
  "sentinels_alert": "Uważne",

  "detail_flora_label": "Flora",
  "flora_none": "-- wybierz --",
  "flora_none2": "Brak",
  "flora_sparse": "Sporadyczna",
  "flora_low": "Skąpa",
  "flora_medium": "Średnia",
  "flora_rich": "Obfita",
  "flora_extreme": "Ekstremalna",

  "detail_fauna_label": "Fauna",
  "fauna_none": "-- wybierz --",
  "fauna_none2": "Brak",
  "fauna_sparse": "Sporadyczna",
  "fauna_low": "Skąpa",
  "fauna_medium": "Średnia",
  "fauna_rich": "Obfita",
  "fauna_extreme": "Ekstremalna",

  "detail_discovered_label": "Odkryty przez",
  "detail_mode_label": "Tryb gry",
  "mode_none": "-- wybierz --",
  "mode_normal": "Normalny",
  "mode_creative": "Kreatywny",
  "mode_survival": "Survival",
  "mode_permadeath": "Permadeath",
  "detail_updated_label": "Zaktualizowano",
  "detail_coords_label": "Koordynaty",
  "detail_portal_btn": "Przejdź do NMS Portals",
  "detail_notes_label": "Notatki",
  "detail_save_btn": "Zapisz detale",

    planet_noSelected: "Brak wybranej planety",
    alert_enterPlanetSystem: "Wprowadź nazwę układu planetarnego aby poprawnie wyświetlić planetę na liście!",
    alert_savedPlanetDetails: "Opis zapisany!",
    unknown_starSystem: "Nieznany układ gwiezdny",
    unknown_planetSystem: "Nieznany układ planetarny",

    "Rainy": "Deszczowy",
    "Lush": "Bujny",
    "Tropical": "Tropikalny",
    "Viridescent": "Zielonkawy",
    "Paradise": "Rajski",
    "Temperate": "Umiarkowana",
    "Humid": "Wilgotny",
    "Overgrown": "Porośnięty",
    "Flourishing": "Kwitnący",
    "Grassy": "Trawiasty",
    "Bountiful": "Obfity",

    "Barren": "Jałowy",
    "Desert": "Pustynny",
    "Rocky": "Skalisty",
    "Bleak": "Ponury",
    "Parched": "Wyschnięty",
    "Abandoned": "Opustoszały",
    "Dusty": "Pylisty",
    "Desolate_barren": "Bezkresny",
    "Wind_swept": "Smagany wiatrem",

    "Terraforming_Catastrophe": "Katastrofa Terraformacji",
    "Dead": "Martwy",
    "Empty": "Pusty",
    "Desolate_dead": "Pustkowie",
    "Lifeless": "Bez życia",
    "Forsaken": "Porzucony",
    "Life_Incompatible": "Niezdatny do życia",
    "Low_Atmosphere": "Niska atmosfera",
    "Airless": "Bezatmosferyczny",
    "Abandoned": "Opuszczony",

    "Fissured": "Szczelinowy",
    "of_Light": "Świetlny",
    "Breached": "Przerwany",
    "Rattling": "Trzaskający",
    "Spined": "Kolczasty",
    "Skeletal": "Szkieletowy",
    "Bubbling": "Bulgoczący",
    "Frothing": "Pieniący się",
    "Foaming": "Pienisty",
    "Contoured": "Profilowany",
    "Cabled": "Okablowany",
    "Webbed": "Sieciowy",
    "Mechanical": "Mechaniczny",
    "Metallic": "Metaliczny",
    "Metallurgic": "Metalurgiczny",
    "Hexagonal": "Sześciokątny",
    "Plated": "Płytowy",
    "Scaly": "Łuskowy",
    "Fungal": "Grzybowy",
    "Sporal": "Zarodnikowy",
    "Capped": "Płetwowy",
    "Finned": "Ostrzowy",
    "Bladed": "Pokryty skorupami",
    "Shell_Strewn": "Zasklepiony",
    "Ossified": "Kostniejący",
    "Petrified": "Skamieniały",
    "Calcified": "Zwapniały",
    "Columned": "Kolumnowy",
	"Pillared": "Słupowy",
    "Sharded": "Rozszczepiony",
    "Shattered": "Zmiażdżony",
    "Fractured": "Pęknięty",
    "Fragmented": "Fragmentaryczny",
    "Crimson": "Karmazynowy",
    "Planetary_Anomaly": "Anomalia Planetarna",
    "Malfunctioning": "Niesprawny",
    "Infected": "Zainfekowany",
    "[REDACTED]": "[ZASTRZEŻONE]",
    "Glassy": "Szklany",
    "Thirsty": "Spragniony",
    "Doomed": "Skazany",
    "Erased": "Wymazany",
    "Temporary": "Tymczasowy",
    "Corrupted": "Uszkodzony",
	
    "Crimson_Red_biome": "Karmazynowy - Czerwony biom",
    "Planetary_Anomaly_Red_biome": "Anomalia Planetarna - Czerwony biom",
    "Planetary_Anomaly_Green_biome": "Anomalia Planetarna - Zielony biom",
    "Planetary_Anomaly_Blue_biome": "Anomalia Planetarna - Niebieski biom",
    "Lost_Green": "Zaginiona Zieleń",
    "Lost_Blue": "Zaginiony Błękit",
    "Lost_Red": "Zaginiona Czerwień",
    "[REDACTED]_Red_biome": "[ZASTRZEŻONE] - Czerwony biom",
    "[REDACTED]_Green_biome": "[ZASTRZEŻONE] - Zielony biom",
    "[REDACTED]_Blue_biome": "[ZASTRZEŻONE] - Niebieski biom",
    "Stellar_Corruption_Detected_Red_biome": "Wykryto Korupcję Gwiezdną - Czerwony biom",
    "Stellar_Corruption_Detected_Green_biome": "Wykryto Korupcję Gwiezdną - Zielony biom",
    "Stellar_Corruption_Detected_Blue_biome": "Wykryto Korupcję Gwiezdną - Niebieski biom",
    "Chromatic_Fog_Red_biome": "Chromatyczna Mgła - Czerwony biom",
    "Chromatic_Fog_Green_biome": "Chromatyczna Mgła - Zielony biom",
    "Chromatic_Fog_Blue_biome": "Chromatyczna Mgła - Niebieski biom",
    "Vile_Anomaly": "Złośliwa Anomalia",
    "Harsh_Blue_Globe": "Surowa Niebieska Planeta",
    "Vermillion_Globe": "Czerwonawy Glob",
    "Toxic_Anomaly": "Toksyczna Anomalia",
    "Frozen_Anomaly": "Zamarznięta Anomalia",
    "Scarlet": "Szkarłatny",
    "Doomed_Jade": "Skazany Szmaragd",
    "Azure": "Azur",
    "Blood": "Krew",
    "Haunted_Emeril": "Nawiedzony Emeril",
    "Cerulean": "Lazurowy",
    "Wine_Dark": "Ciemnoczerwone Wino",
    "Deathly_Green_Anomaly": "Śmiertelna Zielona Anomalia",
    "Ultramarine": "Ultramaryna",

    "Charred": "Zwęglony",
    "Arid": "Suchy",
    "Scorched": "Spalony",
    "Hot": "Gorący",
    "Fiery": "Ognisty",
    "Boiling": "Wrzący",
    "High_Temperature": "Wysoka Temperatura",
    "Torrid": "Parujący",
    "Incandescent": "Rozżarzony",
    "Scalding": "Poparzeniowy",

    "Frozen": "Zamarznięty",
    "Icebound": "Pokryty Lodem",
    "Arctic": "Arktyczny",
    "Glacial": "Lodowcowy",
    "Sub_zero": "Poniżej Zera",
    "Icy": "Lodowy",
    "Frostbound": "Mroźny",
    "Freezing": "Lodowaty",
    "Hiemal": "Zimowy",
    "Hyperborean": "Hiperborejski",

    "Toxic": "Toksyczny",
    "Poisonous": "Trujący",
    "Noxious": "Szkodliwy",
    "Corrosive": "Korozyjny",
    "Acidic": "Kwasowy",
    "Caustic": "Żrący",
    "Acrid": "Ostry",
    "Blighted": "Zniszczony",
    "Miasmatic": "Miasmatyczny",
    "Rotting": "Rozkładający się",

    "Irradiated": "Napromieniowany",
    "Radioactive": "Radioaktywny",
    "Contaminated": "Skażony",
    "Nuclear": "Nuklearny",
    "Isotopic": "Izotopowy",
    "Decaying_Nuclear": "Rozkładający się Nuklearnie",
    "Gamma_Intensive": "Wysokogamowy",
    "High_Radio_Source": "Źródło Wysokiego Promieniowania",
    "Supercritical": "Nadkrytyczny",
    "High_Energy": "Wysokoenergetyczny",

    "Marshy": "Bagienny",
    "Swamp": "Moczarowy",
    "Tropical_Marsh": "Podzwrotnikowy",
    "Foggy": "Mglisty",
    "Misty": "Zamglony",
    "Boggy": "Błotnisty",
    "Endless_Morass": "Nieskończone Bagno",
    "Quagmire": "Grzęzawisko",
    "Hazy": "Lekko Zamglony",
    "Cloudy": "Pochmurny",
    "Vapour": "Parowy",
    "Reeking": "Odorem",
    "Murky": "Mętny",
    "Damp": "Przemoczony",

    "Lava": "Lawa",
    "Magma": "Magma",
    "Erupting": "Wybuchowy",
    "Volcanic": "Wulkaniczny",
    "Ash_Shrouded": "Pokryty Popiołem",
    "Ashen": "Popielaty",
    "Tectonic": "Tektoniczny",
    "Unstable": "Niestabilny",
    "Violent": "Burzliwy",
    "Molten": "Roztopiony",
    "Flame_Ruptured": "Rozżarzony",
    "Imminent_Core_Detonation": "Nadchodząca Detonacja Jądra",
    "Obsidian_Bead": "Obsydianowy",
    "Basalt": "Bazaltowy",


    "Lush": "Bujny",
    "Barren": "Jałowy",
    "Dead": "Martwy",
    "Exotic": "Egzotyczny",
    "Mega_exotic": "Mega Egzotyczny",
    "Scorched": "Spalony",
    "Frozen": "Zamarznięty",
    "Toxic": "Toksyczny",
    "Irradiated": "Napromieniowany",
    "Marsh": "Moczary",
    "Volcanic": "Wulkaniczny",
    "Gas_giant": "Gazowy Gigant",

  },
  "en": {
    "tab_start": "Start",
    "tab_planety": "Planets",
    "tab_punkty": "Points",
    "tab_detale": "Details",
    "start_noPlanets": "Create a new planet or import JSON data",
    "start_addPoint": "Add point",
    "start_label_x": "X (−90 to 90)",
    "start_label_y": "Y (−180 to 180)",
    "start_label_pointName": "Point name",
    "start_label_type": "Type",
    "type_resource": "Resource",
    "type_base": "Base",
    "type_ruins": "Ruins",
    "type_structure": "Structure",
    "type_other": "Other",
    "start_label_notes": "Notes",
    "start_btn_addPoint": "Add point",
    "start_scaling": "Globe and points scaling",
    "start_pointScale": "Point scale",
    "start_pointsDistanceMultiplier": "Bar height",
    "start_globeZoom": "Globe zoom",
    "start_btn_reset": "Reset",
    "start_autoRotate": "Globe auto-rotate",
    "start_importExport": "Import/Export",
    "start_btn_export": "Export JSON",
    "start_languageSelector": "Select language",

    "planet_search_placeholder": "Planet name...",
    "planet_filter_biome": "Biome",
    "planet_filter_biomeAlias": "Biome alias",
    "planet_filter_resource": "Elements",
    "planet_filter_allResources": "All elements",

    "planet_btn_search": "Search",
    "planet_new_name": "New planet name",
    "planet_btn_create": "Create new planet",
    "planet_label_isMoon": "Create as moon",
    "planet_btn_generateName": "Generate name",
    "planet_label_color": "Choose color",
    "planet_texture_url": "Texture URL",
    "planet_btn_setTexture": "Set texture",
    "planet_btn_setColor": "Change color",

    "planet_btn_rename": "Rename",
    "planet_btn_delete": "Delete planet",
    "planet_edit_name": "New planet name",
    "planet_btn_accept": "Accept",
    "planet_btn_cancel": "Cancel",

    "res_copper": "Copper",
    "res_cadmium": "Cadmium",
    "res_emeril": "Emeril",
    "res_indium": "Indium",
    "res_quartz": "Quartz",
    "res_chromatic_metal": "Chromatic Metal",
    "res_paraffinium": "Paraffinium",
    "res_pyrite": "Pyrite",
    "res_ammonia": "Ammonia",
    "res_uranium": "Uranium",
    "res_dioxite": "Dioxite",
    "res_phosphorus": "Phosphorus",
    "res_basalt": "Basalt",
    "res_crystal_helium": "Crystallised Helium",
    "res_lithium": "Lithium",
    "res_cobalt": "Cobalt",
    "res_silver": "Silver",
    "res_gold": "Gold",
    "res_magnetised_ferrite": "Magnetised Ferrite",
    "res_sodium": "Sodium",
    "res_salt": "Salt",
    "res_rusty_metal": "Rusty Metal",

  "points_filter_label": "Filter",
  "points_filter_resource": "Resource",
  "points_filter_base": "Base",
  "points_filter_ruins": "Ruins",
  "points_filter_structure": "Structure",
  "points_filter_other": "Other",
  "points_filter_poles": "Poles",
  "points_filter_myloc": "My Location",
  "points_extra_filters_label": "Additional Filters",
  "points_extra_mined": "Mined",
  "points_extra_visited": "Visited",
  "points_extra_unmined": "Unmined",
  "points_extra_unvisited": "Unvisited",
  "points_sort_label": "Sort",
  "sort_name_asc": "Name A–Z",
  "sort_name_desc": "Name Z–A",
  "sort_type": "Type",
  "sort_newest": "Newest",
  "sort_oldest": "Oldest",

  "detail_galaxy_label": "Galaxy",
  "detail_galaxy_placeholder": "Select galaxy...",
  "detail_star_system_label": "Star System",
  "detail_planet_system_label": "Planetary System",
  "detail_biome_label": "Biome",
  "detail_biome_none": "-- Select biome --",
  "biome_lush": "Lush",
  "biome_barren": "Barren",
  "biome_dead": "Dead",
  "biome_exotic": "Exotic",
  "biome_mega_exotic": "Mega Exotic",
  "biome_hot": "Scorched",
  "biome_frozen": "Frozen",
  "biome_toxic": "Toxic",
  "biome_radioactive": "Radioactive",
  "biome_swamp": "Swamp",
  "biome_volcanic": "Volcanic",
  "biome_gas_giant": "Gas Giant",

  "detail_biome_alias_label": "Biome Alternate Name",
  "detail_biome_alias_none": "-- Select alternate name --",
  "detail_weather_label": "Weather",
  "weather_none": "-- select --",
  "weather_none_atmosphere": "No atmosphere",
  "weather_sunny": "Sunny",
  "weather_cool": "Cool",
  "weather_frosty": "Frosty",
  "weather_warm": "Warm",
  "weather_hot": "Hot",
  "weather_humid": "Humid",
  "weather_rainy": "Rainy",
  "weather_stormy": "Stormy",
  "weather_radioactive": "Radioactive",
  "weather_toxic": "Toxic",
  "weather_acidic": "Acidic",
  "weather_dusty": "Dusty",
  "weather_volcanic": "Volcanic",
  "weather_sandstorm": "Sandstorms",
  "weather_tornado": "Tornadoes",
  "weather_meteor": "Meteors",
  "weather_firestorm": "Firestorms",
  "weather_high_pressure": "High Pressure",
  "weather_low_pressure": "Low Pressure",
  "weather_magnetic": "Magnetic Storms",
  "weather_electric": "Electrical Storms",

  "detail_sentinels_label": "Sentinels",
  "sentinels_none": "-- select --",
  "sentinels_passive": "Passive",
  "sentinels_no": "None",
  "sentinels_relaxed": "Relaxed",
  "sentinels_limited": "Limited",
  "sentinels_low": "Low",
  "sentinels_low_security": "Low Security",
  "sentinels_minimal": "Minimal",
  "sentinels_active": "Active",
  "sentinels_medium": "Medium",
  "sentinels_standard": "Standard",
  "sentinels_typical": "Typical",
  "sentinels_alert": "Alerted",

  "detail_flora_label": "Flora",
  "flora_none": "-- select --",
  "flora_none2": "None",
  "flora_sparse": "Sparse",
  "flora_low": "Low",
  "flora_medium": "Moderate",
  "flora_rich": "Rich",
  "flora_extreme": "Extreme",

  "detail_fauna_label": "Fauna",
  "fauna_none": "-- select --",
  "fauna_none2": "None",
  "fauna_sparse": "Sparse",
  "fauna_low": "Low",
  "fauna_medium": "Moderate",
  "fauna_rich": "Rich",
  "fauna_extreme": "Extreme",

  "detail_discovered_label": "Discovered by",
  "detail_mode_label": "Game Mode",
  "mode_none": "-- select --",
  "mode_normal": "Normal",
  "mode_creative": "Creative",
  "mode_survival": "Survival",
  "mode_permadeath": "Permadeath",
  "detail_updated_label": "Updated",
  "detail_coords_label": "Coordinates",
  "detail_portal_btn": "Go to NMS Portals",
  "detail_notes_label": "Notes",
  "detail_save_btn": "Save details",

    planet_noSelected: "No planet selected",
    alert_enterPlanetSystem: "Enter the planet system name to display the planet correctly in the list!",
    alert_savedPlanetDetails: "Description saved!",
    unknown_starSystem: "Unknown star system",
    unknown_planetSystem: "Unknown planetary system",

    "Rainy": "Rainy",
    "Lush": "Lush",
    "Tropical": "Tropical",
    "Viridescent": "Viridescent",
    "Paradise": "Paradise",
    "Temperate": "Temperate",
    "Humid": "Humid",
    "Overgrown": "Overgrown",
    "Flourishing": "Flourishing",
    "Grassy": "Grassy",
    "Bountiful": "Bountiful",

    "Barren": "Barren",
    "Desert": "Desert",
    "Rocky": "Rocky",
    "Bleak": "Bleak",
    "Parched": "Parched",
    "Abandoned": "Abandoned",
    "Dusty": "Dusty",
    "Desolate_barren": "Desolate",
    "Wind_swept": "Wind-swept",

    "Terraforming_Catastrophe": "Terraforming Catastrophe",
    "Dead": "Dead",
    "Empty": "Empty",
    "Desolate_dead": "Desolate",
    "Lifeless": "Lifeless",
    "Forsaken": "Forsaken",
    "Life_Incompatible": "Life-Incompatible",
    "Low_Atmosphere": "Low Atmosphere",
    "Airless": "Airless",
    "Abandoned": "Abandoned",

    "Fissured": "Fissured",
    "of_Light": "of Light",
    "Breached": "Breached",
    "Rattling": "Rattling",
    "Spined": "Spined",
    "Skeletal": "Skeletal",
    "Bubbling": "Bubbling",
    "Frothing": "Frothing",
    "Foaming": "Foaming",
    "Contoured": "Contoured",
    "Cabled": "Cabled",
    "Webbed": "Webbed",
    "Mechanical": "Mechanical",
    "Metallic": "Metallic",
    "Metallurgic": "Metallurgic",
    "Hexagonal": "Hexagonal",
    "Plated": "Plated",
    "Scaly": "Scaly",
    "Fungal": "Fungal",
    "Sporal": "Sporal",
    "Capped": "Capped",
    "Finned": "Finned",
    "Bladed": "Bladed",
    "Shell_Strewn": "Shell-Strewn",
    "Ossified": "Ossified",
    "Petrified": "Petrified",
    "Calcified": "Calcified",
    "Columned": "Columned",
    "Sharded": "Sharded",
    "Pillared": "Pillared",
    "Shattered": "Shattered",
    "Fractured": "Fractured",
    "Fragmented": "Fragmented",
    "Crimson": "Crimson",
    "Planetary_Anomaly": "Planetary Anomaly",
    "Malfunctioning": "Malfunctioning",
    "Infected": "Infected",
    "[REDACTED]": "[REDACTED]",
    "Glassy": "Glassy",
    "Thirsty": "Thirsty",
    "Doomed": "Doomed",
    "Erased": "Erased",
    "Temporary": "Temporary",
    "Corrupted": "Corrupted",
	
    "Crimson_Red_biome": "Crimson - Red biome",
    "Planetary_Anomaly_Red_biome": "Planetary Anomaly - Red biome",
    "Planetary_Anomaly_Green_biome": "Planetary Anomaly - Green biome",
    "Planetary_Anomaly_Blue_biome": "Planetary Anomaly - Blue biome",
    "Lost_Green": "Lost Green",
    "Lost_Blue": "Lost Blue",
    "Lost_Red": "Lost Red",
    "[REDACTED]_Red_biome": "[REDACTED] - Red biome",
    "[REDACTED]_Green_biome": "[REDACTED] - Green biome",
    "[REDACTED]_Blue_biome": "[REDACTED] - Blue biome",
    "Stellar_Corruption_Detected_Red_biome": "Stellar Corruption Detected - Red biome",
    "Stellar_Corruption_Detected_Green_biome": "Stellar Corruption Detected - Green biome",
    "Stellar_Corruption_Detected_Blue_biome": "Stellar Corruption Detected - Blue biome",
    "Chromatic_Fog_Red_biome": "Chromatic Fog - Red biome",
    "Chromatic_Fog_Green_biome": "Chromatic Fog - Green biome",
    "Chromatic_Fog_Blue_biome": "Chromatic Fog - Blue biome",
    "Vile_Anomaly": "Vile Anomaly",
    "Harsh_Blue_Globe": "Harsh Blue Globe",
    "Vermillion_Globe": "Vermillion Globe",
    "Toxic_Anomaly": "Toxic Anomaly",
    "Frozen_Anomaly": "Frozen Anomaly",
    "Scarlet": "Scarlet",
    "Doomed Jade": "Doomed Jade",
    "Azure": "Azure",
    "Blood": "Blood",
    "Haunted Emeril": "Haunted Emeril",
    "Cerulean": "Cerulean",
    "Wine Dark": "Wine Dark",
    "Deathly_Green_Anomaly": "Deathly Green Anomaly",
    "Ultramarine": "Ultramarine",

    "Charred": "Charred",
    "Arid": "Arid",
    "Scorched": "Scorched",
    "Hot": "Hot",
    "Fiery": "Fiery",
    "Boiling": "Boiling",
    "High_Temperature": "High Temperature",
    "Torrid": "Torrid",
    "Incandescent": "Incandescent",
    "Scalding": "Scalding",

    "Frozen": "Frozen",
    "Icebound": "Icebound",
    "Arctic": "Arctic",
    "Glacial": "Glacial",
    "Sub_zero": "Sub-zero",
    "Icy": "Icy",
    "Frostbound": "Frostbound",
    "Freezing": "Freezing",
    "Hiemal": "Hiemal",
    "Hyperborean": "Hyperborean",

    "Toxic": "Toxic",
    "Poisonous": "Poisonous",
    "Noxious": "Noxious",
    "Corrosive": "Corrosive",
    "Acidic": "Acidic",
    "Caustic": "Caustic",
    "Acrid": "Acrid",
    "Blighted": "Blighted",
    "Miasmatic": "Miasmatic",
    "Rotting": "Rotting",

    "Irradiated": "Irradiated",
    "Radioactive": "Radioactive",
    "Contaminated": "Contaminated",
    "Nuclear": "Nuclear",
    "Isotopic": "Isotopic",
    "Decaying_Nuclear": "Decaying Nuclear",
    "Gamma_Intensive": "Gamma-Intensive",
    "High_Radio_Source": "High Radio Source",
    "Supercritical": "Supercritical",
    "High_Energy": "High Energy",

    "Marshy": "Marshy",
    "Swamp": "Swamp",
    "Tropical_Marsh": "Tropical",
    "Foggy": "Foggy",
    "Misty": "Misty",
    "Boggy": "Boggy",
    "Endless_Morass": "Endless Morass",
    "Quagmire": "Quagmire",
    "Hazy": "Hazy",
    "Cloudy": "Cloudy",
    "Vapour": "Vapour",
    "Reeking": "Reeking",
    "Murky": "Murky",
    "Damp": "Damp",

    "Lava": "Lava",
    "Magma": "Magma",
    "Erupting": "Erupting",
    "Volcanic": "Volcanic",
    "Ash_Shrouded": "Ash-Shrouded",
    "Ashen": "Ashen",
    "Tectonic": "Tectonic",
    "Unstable": "Unstable",
    "Violent": "Violent",
    "Molten": "Molten",
    "Flame_Ruptured": "Flame-Ruptured",
    "Imminent_Core_Detonation": "Imminent Core Detonation",
    "Obsidian_Bead": "Obsidian Bead",
    "Basalt": "Basalt",


    "Lush": "Lush",
    "Barren": "Barren",
    "Dead": "Dead",
    "Exotic": "Exotic",
    "Mega_exotic": "Mega Exotic",
    "Scorched": "Scorched",
    "Frozen": "Frozen",
    "Toxic": "Toxic",
    "Irradiated": "Irradiated",
    "Marsh": "Marsh",
    "Volcanic": "Volcanic",
    "Gas_giant": "Gas Giant",
  }
};
